name: Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Utiliser une version LTS de Node.js

      - name: Install dependencies
        run: npm install
        working-directory: simple-website

      - name: Build Vue.js app
        run: npm run build
        working-directory: simple-website

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'simple-website/dist' # Déployer le dossier de build de Vue.js

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
